stu:
  name: 张三
  age: 20

spring:
  profiles:
    active: test



#日志级别
#logging:
#  file:
#    #使用相对路径的方式设置日志输出的位置（项目根目录目录\my-log\mylog\spring.log）
#    #logging.file.path=my-log/myLog
#    #绝对路径方式将日志文件输出到 【项目所在磁盘根目录\springboot\logging\my\spring.log】
#    path: my-log/myLog
#  pattern:
#    #控制台日志输出格式
#    console: %d{yyyy-MM-dd hh:mm:ss} [%thread] %-5level %logger{50} - %msg%n
#    #日志文件输出格式
#    file: %d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n
#  level:
#    com:
#    bachan: trace